### ISSUE TITLE
Commit 메시지는 중요합니다.

### ISSUE THREAD

**Issue by stunstunstun** [dl0312/Higher-Lower-Kor#2]
프로젝트에 강제로 `commitlint`를 적용해서 좋은 Commit 메시지를 작성하는 습관을 만들어보세요. 실무에서 협업시에 가장 필요한 습관입니다.

- https://github.com/marionebl/commitlint

**Comment by dl0312** [comment]
https://github.com/dl0312/Higher-Lower-Kor/blob/master/commitlint.config.js
`commitlint`를 적용해서 `commit`을 해봤습니다. 감사합니다.
