### ISSUE TITLE
Travis CI를 연동해보세요.

### ISSUE THREAD

**Issue by stunstunstun** [dl0312/Higher-Lower-Kor#4]
CI는 Branch에 변경내역이 생기면 프로젝트가 유효한지 자동으로 검증해주는 일종의 서버입니다. `package.json`에 정의된 명령이 유효한지 체크하는 정도로 시작해보세요.

- https://docs.travis-ci.com/user/tutorial/

```
$ yarn install && yarn build
```

**Comment by dl0312** [comment]
Resolve #4 Integration with Travis CI

**Comment by stunstunstun** [comment]
@dl0312 You Did!
